version: 2
jobs: 
  build:
    docker: 
      - image: circleci/node:12.13
    working_directory: ~/hello-world-ci
    steps:
        - checkout
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
        - run: npm ci
        - save_cache:
            paths: 
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
        fingerprints:
          - 63:67:5f:9f:23:cb:b8:b7:0a:f4:3b:62:4f:df:28:26
      - run:
        name: Deploy Over SSH
        command: |
          ssh $SSH_USER@SSH_HOST "cd ~/apps/hello-world-ci && git pull origin master"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master